[package]
name = "build-archiver"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
zip = {version = "5.1.1", features = ["lzma"]}
log = "0.4.28"
pretty_env_logger = "0.5.0"
anyhow = "1.0.99"